source 'https://github.com/CocoaPods/Specs.git'

target 'WebHere', :exclusive => true do
    pod "WebHere", :path => "../"
end

target 'libWebHereTests', :exclusive => true do
    platform :osx, '10.10'
    pod "WebHere", :path => "../"
    pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
    pod 'Expecta'
    pod 'Nocilla'
end

post_install do |installer|
    installer.project.targets.each do |target|
        puts target.name
    end
end