workspace 'WebHereTest.xcworkspace'
xcodeproj 'WebHereTest/WebHereTest.xcodeproj'

def pods_core
end

def pods_test
  pod 'OCMock'
  pod 'Expecta'
  pod 'Nocilla'
end

target :WebHereTest do
  xcodeproj 'WebHereTest/WebHereTest.xcodeproj'
  platform :ios, '7.0'
  pods_core

  target :WebHereTests, :exclusive => true do
    pods_test
  end
end